### PR TITLE
Moved repository

### PR DESCRIPTION
**Pull request by yrn1**

### CODE REVIEW

**Comment by bparticle** [comment]
Something broke with the GitHub releases on the docs because your repo isn't showing up, will look into it asap (something to do with the latest() function that tomf contributed I think.

**Comment by yrn1** [comment]
I noticed it too. Could also be my fault cause I renamed releases and updated the regex to match them. Maybe something wrong there?

**Comment by bparticle** [comment]
Yeah but that function should be able to catch exceptions if the repo exists

**Comment by bparticle** [comment]
Ah okay I get it, the function is actually testing the regex to the tagname
```
return releases.filter(
  (release) => !!(release.tag_name || '').match(regex)
)
```
The tagname in the FilterDelays repo releases is numbers only. Maybe we can extend the filter to search in the **name** key as well.

**Comment by yrn1** [comment]
Or I could just create extra tags… will do when I get home from the beach 🏖

**Comment by bparticle** [comment]
Haha, stay on the beach, it's done

**Comment by yrn1** [comment]
Nice. Thanks!

**Pull request merged**
